-- ROUND, HAVING
-- WHERE ~ NOT IN
SELECT c.CAR_ID,
       c.CAR_TYPE,
       ROUND(c.DAILY_FEE * 30 * (1 - p.DISCOUNT_RATE/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR c
         JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN p
              ON c.CAR_TYPE = p.CAR_TYPE
WHERE c.CAR_TYPE IN ('세단', 'SUV') AND
        p.DURATION_TYPE = '30일 이상' AND
        c.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE >= '2022-11-01' AND
                START_DATE <= '2022-11-30'
        )
HAVING  500000 <= FEE AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;